config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'invoices#index'
  resources :users, only: [:new, :create, :show]
  get 'invoices/sync_invoices', to: 'invoices#sync_invoices', as: :sync_invoices
  resources :invoices, only: [:new, :create, :show]
  resources :collection_item, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection_item.rb
class CollectionItem < ApplicationRecord
  validates :amount, presence: true
  validates :collection_date, presence: true

  before_create do
    self.invoice_id = Invoice.find_by(reference: reference).id
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :collection_items
  validates :brand_manager, presence: true
  validates :amount, presence: true
  validates :customer_name, presence: true
  validates :invoice_date, presence: true
  validates :narration, presence: true
  validates :reference, presence: true, uniqueness: true

  scope :total_invoices_count, -> {count('*')}

  scope :collected_bills, -> {joins(:collection_items).select('invoices.*')}
  scope :pending_bills, -> {left_joins(:collection_items).where(collection_items: {id: nil}).select('invoices.*')}

  def total_collection_amount
    return collection_items.sum(&:amount) if collection_items.present?
    0
  end

  def balance_due
    amount - total_collection_amount
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: :true, length: {maximum: 50}
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: :true, length: {maximum: 200},
            format: {with: EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :password, presence: :true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collection_item_controller.rb
class CollectionItemController < ApplicationController
  def create
    @collction_item = CollectionItem.create(collection_item_params)
  end

  private

  def collection_item_params
    params.require(:collection_item).permit(:amount, :collection_date, :reference)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show]

  def index
    respond_to do |format|
      format.js do
        if params[:type] == 'nf'
          @invoice = Invoice.new
        elsif params[:type] == 'pb'
          @invoices = Invoice.pending_bills
        elsif params[:type] == 'cb'
          @invoices = Invoice.collected_bills
        elsif params[:type] == 'add_collection'
          @collection = CollectionItem.new
        else
          @invoices = Invoice.all
        end
      end
      format.html {@invoices = Invoice.all}
    end
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.create(invoice_params)
  end

  def show

  end

  def sync_invoices
    collection_item = File.open('collections.json').read
    invoice_file = File.open('new_invoices.json').read
    if invoice_file.length > 0
      InvoiceParserWorker.perform_async(invoice_file, collection_item)
    end
    redirect_to root_path
  end

  private

  def invoice_params
    params.require(:invoice).permit(:brand_manager,
                                    :amount,
                                    :customer_name,
                                    :invoice_date,
                                    :narration,
                                    :reference)
  end

  def set_invoice
    @invoice = Invoice.find_by(id: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.errors.any?
      ''
    else
      ''
    end
  end

  def show
    if @user.authenticate(params[:password])
      ''
    else
      ''
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find_by email: params[:email]
    return if @user.present?
    redirect_to request.reffer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collection_item_helper.rb
module CollectionItemHelper

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/invoices/_add_new_bill.html.erb
<%= form_with model: @invoice, data: {remote: true} do |f| %>
  <div class="field">
    <label class="label">Reference</label>
    <p class="control">
      <%= f.text_field :reference, class: 'input', required: true, placeholder: 'Name of Schedule To Be Created' %>
    </p>
  </div>

  <div class="field">
    <label class="label">Invoice Date</label>
    <p class="control">
      <%= f.text_field :invoice_date, class: 'input', required: true, placeholder: 'Name of Schedule To Be Created' %>
    </p>
  </div>

  <div class="field">
    <label class="label">Customer</label>
    <p class="control">
      <%= f.text_field :customer, class: 'input', required: true, placeholder: 'Name of Schedule To Be Created' %>
    </p>
  </div>

  <div class="field">
    <label class="label">Brand Manger</label>
    <p class="control">
      <%= f.text_field :brand_manager, class: 'input', required: true, placeholder: 'Name of Schedule To Be Created' %>
    </p>
  </div>

  <div class="field">
    <label class="label">Narration</label>
    <p class="control">
      <%= f.text_field :narration, class: 'input', required: true, placeholder: 'Name of Schedule To Be Created' %>
    </p>
  </div>

  <div class="field">
    <label class="label">Reference</label>
    <p class="control">
      <%= f.text_field :amount, class: 'input', required: true, placeholder: 'Name of Schedule To Be Created' %>
    </p>
  </div>


  <hr style="width: auto">


  <div class="field has-addons">
    <%= f.submit nil, class: 'button is-success', style: "margin-right: 15px;" %>
  </div>

<% end %>

app/views/invoices/_collection_modal.html.erb
<div class="modal new-tally-connection-modal is-active">
  <div class="modal-background" data-dismiss="modal"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">Create a new Tally Connection</p>
      <button data-dismiss="modal" class="delete"></button>
    </header>
    <%= form_with url: collection_item_index_path, data: {remote: true} do |f| %>
      <section class="modal-card-body">
        <div class="field">
          <label class="label">Amount</label>
          <p class="control">
            <%= f.text_field 'collection_item[amount]', class: 'input', required: true %>
          </p>
        </div>

        <div class="field">
          <label class="label">Collection Date</label>
          <p class="control">
            <%= f.date_field 'collection_item[collection_date]', class: 'input', required: true %>
          </p>
        </div>

        <div class="field">
          <label class="label">Reference</label>
          <p class="control">
            <%= f.text_field 'collection_item[reference]', class: 'input', required: true, value: reference %>
          </p>
        </div>

      </section>
      <footer class="modal-card-foot">
        <%= f.submit nil, class: 'button is-primary' %>
        <a data-dismiss="modal" class="button">Cancel</a>
      </footer>
    <% end %>
  </div>
</div>

app/views/invoices/_invoice_data_row.html.erb
<tr>
  <td>
    <%= link_to invoice.reference, invoice_path(invoice) %></td>
  <td>
    <%= invoice.invoice_date %></td>
  <td>
    <%= invoice.customer_name %></td>
  <td>
    <%= invoice.brand_manager %></td>
  <td>
    <%= invoice.narration %></td>
  <td>
    <%= invoice.amount %></td>
  <td>
    <%= invoice.total_collection_amount %></td>
  <td>
    <%= invoice.balance_due %></td>
  <td><%= link_to 'Add Collection', root_path(type: 'add_collection', invoice_id: invoice.id, reference: invoice.reference), data: {remote: true} %></td>
</tr>

app/views/invoices/index.html.erb
<div class="box">
  <div class="columns" style="padding: 20px;">
    <div class="column">
      <%= link_to 'Add a New Bill', root_path(type: 'nf'), class: 'button is-primary', data: {remote: true} %>
    </div>

    <div class="column">
      <%= link_to 'Show Pending Bills', root_path(type: 'pb'), class: 'button is-primary', data: {remote: true} %>
    </div>

    <div class="column">
      <%= link_to 'Show Collected Bills', root_path(type: 'cb'), class: 'button is-primary', data: {remote: true} %>
    </div>

    <div class="column">
      <%= link_to 'Sync Invoices', sync_invoices_path, class: 'button is-primary' %>
    </div>

    <div class="column">
      <%= link_to 'Reload', root_path, class: 'button is-primary' %>
    </div>

  </div>
  <% if @invoices.present? %>
    <table class="table" data-id="invoice-table">
      <thead>
      <tr>
        <th>Reference</th>
        <th>Invoice Date</th>
        <th>Customer</th>
        <th>Brand Manager</th>
        <th>Narration</th>
        <th>Amount</th>
        <th>Total Collection</th>
        <th>Balance Due</th>
        <th>Add Collection</th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: 'invoice_data_row', collection: @invoices, as: :invoice %>

      </tbody>
    </table>
  <% else %>
    <p class="">There is no invoices are present.. please click sync invoices button</p>
  <% end %>
</div>

<div data-id="new-form" class="is-hidden">

</div>


<div data-id="colletion-modal">

</div>

app/views/invoices/index.js.erb
invoiceTable = $("[data-id='invoice-table']")
colletionModal = $("[data-id='colletion-modal']")
newForm = $("[data-id='new-form']")
<% if params[:type] == 'nf' %>
invoiceTable.addClass('is-hidden')
newForm.html("<%= j render partial: 'add_new_bill' %>")
newForm.removeClass('is-hidden')
<% elsif params[:type] == 'add_collection' %>
colletionModal.html('<%= j render partial: 'collection_modal', locals: {reference: params[:reference]} %>')
<% else %>
invoiceTable.find('tbody').empty()
invoiceTable.find('tbody').html("<%= j render partial: 'invoice_data_row', collection: @invoices , as: :invoice%>")
invoiceTable.removeClass('is-hidden')
<% end %>

app/views/invoices/show.html.erb
<%= link_to 'back', root_path %>
<div>
  <p>
    <%= @invoice.reference %></p>
  <p>
    <%= @invoice.invoice_date %></p>
  <p>
    <%= @invoice.customer_name %></p>
  <p>
    <%= @invoice.brand_manager %></p>
  <p>
    <%= @invoice.narration %></p>
  <p>
    <%= @invoice.amount %></p>
  <p>
    <%= @invoice.total_collection_amount %></p>
  <p>
    <%= @invoice.balance_due %></p>
  <p><%= link_to 'Add Collection', root_path(type: 'add_collection', invoice_id: @invoice.id, reference: @invoice.reference), data: {remote: true} %></p>
</div>

<div data-id="colletion-modal">

</div>

app/views/invoices/sync_invoices.html.erb
<div data-id="current-parser-progerss">
  <p>Invoice Processing</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AxbInvoicing</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar app-navbar" style="background-color: #00d1b2">
  <div class="container">

    <div class="navbar-brand" style="z-index: 1 ;">
      <a class="navbar-item" href="<%= root_path %>">
        <div class="logo">
        </div>
      </a>
    </div>

    <div class="navbar-menu">

      <div class="navbar-item">

      </div>
    </div>
  </div>
</nav>
<br>
<%= yield %>
</body>
</html>

app/views/users/new.html.erb
<h1>hai</h1>